### ISSUE TITLE
Add package to Pypi and make it installable with pip

### ISSUE THREAD

**Issue by olifante** [kux/django-admin-extend#3]
Just used your code to add an admin action to a 3rd party model, and it worked like a charm.

It would be nice it could be installed with pip from Pypi. As it is, I had to manually copy your extend.py into my app. Not too bad, but I usually prefer to manage all dependencies via my requirements.txt file.

Thanks for the useful work.

**Comment by kux** [comment]
https://pypi.python.org/pypi/django-admin-extend/0.0.3

I had to bump the version a couple of times as I added things in a rush and got the download url wrong the first time.
